apiVersion: apps/v1
kind: Deployment
metadata:
  name: ${MODEL_DEPLOYMENT_NAME}
  labels:
    app: ${MODEL_APP_LABEL}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ${MODEL_APP_LABEL}
  template:
    metadata:
      labels:
        app: ${MODEL_APP_LABEL}
    spec:
      nodeSelector:
        cloud.google.com/gke-nodepool: gpu-pool
      
      tolerations:
      - key: "nvidia.com/gpu"
        operator: "Equal"
        value: "present"
        effect: "NoSchedule"

      containers:
        - name: api
          image: ${PLACEHOLDER_IMAGE}
          ports:
            - containerPort: 8081
          env:
            - name: PORT
              value: "8081"
          
          volumeMounts:
          - name: dshm
            mountPath: /dev/shm

          resources:
            requests:
              cpu: "1"
              memory: "8Gi"
            limits:
              cpu: "2"
              memory: "12Gi"
              nvidia.com/gpu: "1"

          readinessProbe:
            httpGet:
              path: /health
              port: 8081
            initialDelaySeconds: 120
          
      volumes:
      - name: dshm
        emptyDir:
          medium: Memory