import { useEffect, useState } from "react";
import axios from "../api/axiosClient";
import {
  ExternalLink,
  Loader2,
  Rocket,
  Sparkles,
  RefreshCw,
} from "lucide-react";
import { Button } from "@/components/ui/button";
import ImageGenerationModal from "../components/ImageGenerationModal";

export default function GalleryPage() {
  const [images, setImages] = useState([]);
  const [deployments, setDeployments] = useState([]);
  const [loading, setLoading] = useState(true);
  const [refreshing, setRefreshing] = useState(false);
  const [isModalOpen, setIsModalOpen] = useState(false);
  const fetchGallery = async (isManualRefresh = false) => {
    if (isManualRefresh) setRefreshing(true);

    try {
      const res = await axios.get("/images/gallery");
      setImages(res.data);
    } catch (error) {
      console.error("Failed to load gallery", error);
    } finally {
      if (isManualRefresh) setRefreshing(false);
    }
  };

  useEffect(() => {
    const fetchInitialData = async () => {
      try {
        setLoading(true);
        const [galleryRes, deploymentsRes] = await Promise.all([
          axios.get("/images/gallery"),
          axios.get("/deployments/"),
        ]);

        setImages(galleryRes.data);
        setDeployments(deploymentsRes.data);
      } catch (error) {
        console.error("Failed to load data", error);
      } finally {
        setLoading(false);
      }
    };
    fetchInitialData();
  }, []);

  const handleNewImage = (newImage) => {
    setImages((prev) => [newImage, ...prev]);
  };

  if (loading) {
    return (
      <div className="flex justify-center items-center h-screen bg-slate-900">
        <Loader2 className="w-10 h-10 animate-spin text-emerald-500" />
      </div>
    );
  }

  return (
    <div className="min-h-screen bg-gray-900/70 p-8 font-sans text-slate-300">
      <div className="max-w-7xl mx-auto">
        <div className="mb-8 border-b border-slate-700/50 pb-6 flex flex-col sm:flex-row justify-between items-start sm:items-center gap-4">
          <div>
            <h1 className="text-3xl font-bold text-white mb-2 flex items-center gap-3">
              <ExternalLink className="w-8 h-8 text-emerald-500" />
              Creation Gallery
            </h1>
            <p className="text-slate-400">
              All images generated by your models.
            </p>
          </div>

          <div className="flex items-center gap-3">
            <Button
              onClick={() => fetchGallery(true)}
              disabled={refreshing}
              className="bg-emerald-600 text-white px-5 py-2 rounded-lg flex items-center gap-2 transition-all hover:bg-emerald-700 disabled:bg-slate-600 disabled:cursor-not-allowed shadow-lg shadow-emerald-900/20"
            >
              <RefreshCw
                className={`w-4 h-4 ${refreshing ? "animate-spin" : ""}`}
              />
              {refreshing ? "Refreshing..." : "Refresh"}
            </Button>

            <Button
              onClick={() => setIsModalOpen(true)}
              disabled={deployments.length === 0}
              className="bg-emerald-600 text-white px-5 py-2 rounded-lg flex items-center gap-2 transition-all hover:bg-emerald-700 disabled:bg-slate-600 disabled:cursor-not-allowed shadow-lg shadow-emerald-900/20"
            >
              <Sparkles className="w-4 h-4" />
              Generate Image
            </Button>
          </div>
        </div>

        {images.length === 0 ? (
          <div className="text-center py-20 bg-slate-800/30 rounded-xl border border-dashed border-slate-700">
            <Rocket className="w-12 h-12 text-slate-600 mx-auto mb-4" />
            <h3 className="text-lg font-medium text-white">No images yet</h3>
            <Button
              variant="link"
              onClick={() => setIsModalOpen(true)}
              className="text-emerald-400"
            >
              Click here to generate your first one
            </Button>
          </div>
        ) : (
          <div className="grid grid-cols-1 sm:grid-cols-2 md:grid-cols-3 lg:grid-cols-4 gap-6">
            {images.map((img) => (
              <div
                key={img.id}
                className="group bg-slate-800 rounded-xl border border-slate-700 overflow-hidden hover:border-emerald-500/50 transition-all shadow-lg hover:shadow-emerald-900/20"
              >
                <a
                  href={img.image_url}
                  target="_blank"
                  rel="noreferrer"
                  className="block relative aspect-square bg-slate-900"
                >
                  <img
                    src={img.image_url}
                    alt={img.prompt}
                    className="w-full h-full object-cover transition-transform duration-500 group-hover:scale-105"
                    loading="lazy"
                  />
                  <div className="absolute inset-0 bg-black/70 opacity-0 group-hover:opacity-100 transition-opacity duration-300 flex items-center justify-center p-4">
                    <p className="text-xs text-white text-center italic line-clamp-4">
                      "{img.prompt}"
                    </p>
                  </div>
                </a>
                <div className="p-4 border-t border-slate-700/50">
                  <span
                    className="text-sm font-bold text-white truncate block"
                    title={img.project_name}
                  >
                    {img.project_name}
                  </span>
                  <div className="flex justify-between items-center mt-2 text-xs text-slate-500">
                    <span className="bg-slate-700/50 px-2 py-0.5 rounded">
                      Dep #{img.deployment_id}
                    </span>
                    <span>{new Date(img.created_at).toLocaleDateString()}</span>
                  </div>
                </div>
              </div>
            ))}
          </div>
        )}

        <ImageGenerationModal
          isOpen={isModalOpen}
          onClose={() => setIsModalOpen(false)}
          deployments={deployments}
          onSuccess={handleNewImage}
        />
      </div>
    </div>
  );
}
